# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false

reviews:
  profile: "chill"
  high_level_summary: true
  review_status: true
  review_details: false
  commit_status: true
  request_changes_workflow: false
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
  tools:
    github-checks:
      enabled: true
      timeout_ms: 120000
    actionlint:
      enabled: true
    markdownlint:
      enabled: true
    gitleaks:
      enabled: true

chat:
  auto_reply: true
