// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  ownerUserId: __t.u64().name("owner_user_id"),
  managerUserId: __t.u64().name("manager_user_id"),
  projectId: __t.u64().name("project_id"),
  name: __t.string(),
  role: __t.string(),
  department: __t.string(),
  description: __t.string(),
  status: __t.string(),
  autonomyMode: __t.string().name("autonomy_mode"),
  approvalMode: __t.string().name("approval_mode"),
  toolsJson: __t.string().name("tools_json"),
  scheduleJson: __t.string().name("schedule_json"),
  dailyBudgetMicrousd: __t.u64().name("daily_budget_microusd"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
