// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  agentId: __t.u64().primaryKey().name("agent_id"),
  orgId: __t.u64().name("org_id"),
  adapterType: __t.string().name("adapter_type"),
  runtimeStatus: __t.string().name("runtime_status"),
  baseUrl: __t.string().name("base_url"),
  command: __t.string(),
  cwd: __t.string(),
  envJson: __t.string().name("env_json"),
  configJson: __t.string().name("config_json"),
  heartbeatPolicyJson: __t.string().name("heartbeat_policy_json"),
  wakePolicyJson: __t.string().name("wake_policy_json"),
  lastHeartbeatAt: __t.u64().name("last_heartbeat_at"),
  lastSuccessAt: __t.u64().name("last_success_at"),
  lastFailureAt: __t.u64().name("last_failure_at"),
  lastError: __t.string().name("last_error"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
