// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  agentId: __t.u64().name("agent_id"),
  runId: __t.u64().name("run_id"),
  adapterType: __t.string().name("adapter_type"),
  externalSessionId: __t.string().name("external_session_id"),
  status: __t.string(),
  summary: __t.string(),
  metadataJson: __t.string().name("metadata_json"),
  lastSeenAt: __t.u64().name("last_seen_at"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
