// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  taskId: __t.u64().name("task_id"),
  agentId: __t.u64().name("agent_id"),
  requesterUserId: __t.u64().name("requester_user_id"),
  reviewerUserId: __t.u64().name("reviewer_user_id"),
  title: __t.string(),
  summary: __t.string(),
  status: __t.string(),
  riskLevel: __t.string().name("risk_level"),
  actionType: __t.string().name("action_type"),
  metadataJson: __t.string().name("metadata_json"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
  decidedAt: __t.u64().name("decided_at"),
});
