// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  taskId: __t.u64().name("task_id"),
  agentId: __t.u64().name("agent_id"),
  status: __t.string(),
  triggerType: __t.string().name("trigger_type"),
  summary: __t.string(),
  errorMessage: __t.string().name("error_message"),
  tokenInput: __t.u64().name("token_input"),
  tokenOutput: __t.u64().name("token_output"),
  toolCalls: __t.u64().name("tool_calls"),
  costMicrousd: __t.u64().name("cost_microusd"),
  startedAt: __t.u64().name("started_at"),
  finishedAt: __t.u64().name("finished_at"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
