// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  projectId: __t.u64().name("project_id"),
  goalId: __t.u64().name("goal_id"),
  agentId: __t.u64().name("agent_id"),
  createdByUserId: __t.u64().name("created_by_user_id"),
  title: __t.string(),
  description: __t.string(),
  status: __t.string(),
  priority: __t.string(),
  sourceType: __t.string().name("source_type"),
  linkedEntityType: __t.string().name("linked_entity_type"),
  linkedEntityId: __t.u64().name("linked_entity_id"),
  dueAt: __t.u64().name("due_at"),
  completedAt: __t.u64().name("completed_at"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
