// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  agentId: __t.u64().name("agent_id"),
  taskId: __t.u64().name("task_id"),
  requestedByUserId: __t.u64().name("requested_by_user_id"),
  status: __t.string(),
  source: __t.string(),
  reason: __t.string(),
  payloadJson: __t.string().name("payload_json"),
  runId: __t.u64().name("run_id"),
  errorMessage: __t.string().name("error_message"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
  startedAt: __t.u64().name("started_at"),
  finishedAt: __t.u64().name("finished_at"),
});
