// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  orgId: __t.u64().primaryKey().name("org_id"),
  createdByUserId: __t.u64().name("created_by_user_id"),
  defaultModel: __t.string().name("default_model"),
  autonomyPosture: __t.string().name("autonomy_posture"),
  fallbackMode: __t.string().name("fallback_mode"),
  externalSendPolicy: __t.string().name("external_send_policy"),
  budgetChangePolicy: __t.string().name("budget_change_policy"),
  internalNotesPolicy: __t.string().name("internal_notes_policy"),
  integrationsJson: __t.string().name("integrations_json"),
  auditRetentionDays: __t.u64().name("audit_retention_days"),
  maxRunCostMicrousd: __t.u64().name("max_run_cost_microusd"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
