// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  channelId: __t.u64().name("channel_id"),
  visibility: __t.string(),
  title: __t.string(),
  description: __t.string(),
  scheduledAt: __t.u64().name("scheduled_at"),
  dyteMeetingId: __t.string().name("dyte_meeting_id"),
  createdByUserId: __t.u64().name("created_by_user_id"),
  status: __t.string(),
  startedCallSessionId: __t.u64().name("started_call_session_id"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
