// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  channelId: __t.u64().name("channel_id"),
  orgId: __t.u64().name("org_id"),
  dyteMeetingId: __t.string().name("dyte_meeting_id"),
  title: __t.string(),
  startedByUserId: __t.u64().name("started_by_user_id"),
  status: __t.string(),
  startedAt: __t.u64().name("started_at"),
  endedAt: __t.u64().name("ended_at"),
  updatedAt: __t.u64().name("updated_at"),
});
