// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  orgId: __t.u64(),
  projectId: __t.u64(),
  managerUserId: __t.u64(),
  name: __t.string(),
  role: __t.string(),
  department: __t.string(),
  description: __t.string(),
  status: __t.string(),
  autonomyMode: __t.string(),
  approvalMode: __t.string(),
  toolsJson: __t.string(),
  scheduleJson: __t.string(),
  dailyBudgetMicrousd: __t.u64(),
};
