// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  orgId: __t.u64(),
  projectId: __t.u64(),
  goalId: __t.u64(),
  agentId: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  priority: __t.string(),
  sourceType: __t.string(),
  linkedEntityType: __t.string(),
  linkedEntityId: __t.u64(),
  dueAt: __t.u64(),
};
