// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddChannelMemberReducer from "./add_channel_member_reducer";
import ApproveMeetingBookingReducer from "./approve_meeting_booking_reducer";
import CancelMeetingBookingReducer from "./cancel_meeting_booking_reducer";
import CancelMeetingBookingByTokenReducer from "./cancel_meeting_booking_by_token_reducer";
import CancelScheduledMeetingReducer from "./cancel_scheduled_meeting_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import CreateInviteReducer from "./create_invite_reducer";
import CreateMeetingBookingReducer from "./create_meeting_booking_reducer";
import CreateMeetingEventTypeReducer from "./create_meeting_event_type_reducer";
import CreateMeetingFollowupTemplateReducer from "./create_meeting_followup_template_reducer";
import CreateOrganizationReducer from "./create_organization_reducer";
import CreateScheduledMeetingReducer from "./create_scheduled_meeting_reducer";
import EditMessageReducer from "./edit_message_reducer";
import EndChannelCallReducer from "./end_channel_call_reducer";
import GenerateJoinIdReducer from "./generate_join_id_reducer";
import HeartbeatReducer from "./heartbeat_reducer";
import JoinChannelCallReducer from "./join_channel_call_reducer";
import JoinOrganizationReducer from "./join_organization_reducer";
import JoinScheduledMeetingReducer from "./join_scheduled_meeting_reducer";
import LeaveChannelCallReducer from "./leave_channel_call_reducer";
import MarkChannelReadReducer from "./mark_channel_read_reducer";
import MarkMeetingReminderDeliveryStatusReducer from "./mark_meeting_reminder_delivery_status_reducer";
import QueueMeetingReminderDeliveriesReducer from "./queue_meeting_reminder_deliveries_reducer";
import RegisterUserReducer from "./register_user_reducer";
import RejectMeetingBookingReducer from "./reject_meeting_booking_reducer";
import RescheduleMeetingBookingReducer from "./reschedule_meeting_booking_reducer";
import RescheduleMeetingBookingByTokenReducer from "./reschedule_meeting_booking_by_token_reducer";
import RescheduleScheduledMeetingReducer from "./reschedule_scheduled_meeting_reducer";
import SendMessageReducer from "./send_message_reducer";
import SetMeetingAvailabilityRulesReducer from "./set_meeting_availability_rules_reducer";
import SetMeetingRecordingPolicyReducer from "./set_meeting_recording_policy_reducer";
import SetMeetingReminderTemplateReducer from "./set_meeting_reminder_template_reducer";
import SetTypingReducer from "./set_typing_reducer";
import StartChannelCallReducer from "./start_channel_call_reducer";
import ToggleReactionReducer from "./toggle_reaction_reducer";
import UpdateMeetingEventTypeReducer from "./update_meeting_event_type_reducer";
import UpdateProfileReducer from "./update_profile_reducer";
import UpdateScheduledMeetingReducer from "./update_scheduled_meeting_reducer";
import UpsertMeetingPublicProfileReducer from "./upsert_meeting_public_profile_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ChatCallParticipantRow from "./chat_call_participant_table";
import ChatCallSessionRow from "./chat_call_session_table";
import ChatChannelRow from "./chat_channel_table";
import ChatChannelMemberRow from "./chat_channel_member_table";
import ChatMessageRow from "./chat_message_table";
import ChatReactionRow from "./chat_reaction_table";
import ChatReadStateRow from "./chat_read_state_table";
import ChatScheduledMeetingRow from "./chat_scheduled_meeting_table";
import ChatTypingRow from "./chat_typing_table";
import InviteRow from "./invite_table";
import JoinIdRow from "./join_id_table";
import MeetingActivityRow from "./meeting_activity_table";
import MeetingAvailabilityRuleRow from "./meeting_availability_rule_table";
import MeetingBookingRow from "./meeting_booking_table";
import MeetingEventTypeRow from "./meeting_event_type_table";
import MeetingFollowupTemplateRow from "./meeting_followup_template_table";
import MeetingPublicProfileRow from "./meeting_public_profile_table";
import MeetingRecordingPolicyRow from "./meeting_recording_policy_table";
import MeetingReminderDeliveryRow from "./meeting_reminder_delivery_table";
import MeetingReminderTemplateRow from "./meeting_reminder_template_table";
import OrganizationRow from "./organization_table";
import OrganizationMemberRow from "./organization_member_table";
import UserRow from "./user_table";
import UserPresenceRow from "./user_presence_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  chat_call_participant: __table({
    name: 'chat_call_participant',
    indexes: [
      { name: 'call_session_id', algorithm: 'btree', columns: [
        'callSessionId',
      ] },
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'chat_call_participant_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatCallParticipantRow),
  chat_call_session: __table({
    name: 'chat_call_session',
    indexes: [
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
      { name: 'started_by_user_id', algorithm: 'btree', columns: [
        'startedByUserId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'chat_call_session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatCallSessionRow),
  chat_channel: __table({
    name: 'chat_channel',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
    ],
    constraints: [
      { name: 'chat_channel_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatChannelRow),
  chat_channel_member: __table({
    name: 'chat_channel_member',
    indexes: [
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'chat_channel_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatChannelMemberRow),
  chat_message: __table({
    name: 'chat_message',
    indexes: [
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'parent_message_id', algorithm: 'btree', columns: [
        'parentMessageId',
      ] },
      { name: 'sender_id', algorithm: 'btree', columns: [
        'senderId',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  chat_reaction: __table({
    name: 'chat_reaction',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'message_id', algorithm: 'btree', columns: [
        'messageId',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'chat_reaction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatReactionRow),
  chat_read_state: __table({
    name: 'chat_read_state',
    indexes: [
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'chat_read_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatReadStateRow),
  chat_scheduled_meeting: __table({
    name: 'chat_scheduled_meeting',
    indexes: [
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'created_by_user_id', algorithm: 'btree', columns: [
        'createdByUserId',
      ] },
      { name: 'dyte_meeting_id', algorithm: 'btree', columns: [
        'dyteMeetingId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
      { name: 'scheduled_at', algorithm: 'btree', columns: [
        'scheduledAt',
      ] },
      { name: 'started_call_session_id', algorithm: 'btree', columns: [
        'startedCallSessionId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'visibility', algorithm: 'btree', columns: [
        'visibility',
      ] },
    ],
    constraints: [
      { name: 'chat_scheduled_meeting_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatScheduledMeetingRow),
  chat_typing: __table({
    name: 'chat_typing',
    indexes: [
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'chat_typing_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatTypingRow),
  invite: __table({
    name: 'invite',
    indexes: [
      { name: 'email', algorithm: 'btree', columns: [
        'email',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
    ],
    constraints: [
      { name: 'invite_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InviteRow),
  join_id: __table({
    name: 'join_id',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
      { name: 'token', algorithm: 'btree', columns: [
        'token',
      ] },
    ],
    constraints: [
      { name: 'join_id_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'join_id_token_key', constraint: 'unique', columns: ['token'] },
    ],
  }, JoinIdRow),
  meeting_activity: __table({
    name: 'meeting_activity',
    indexes: [
      { name: 'actor_user_id', algorithm: 'btree', columns: [
        'actorUserId',
      ] },
      { name: 'booking_id', algorithm: 'btree', columns: [
        'bookingId',
      ] },
      { name: 'created_at', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { name: 'event_type', algorithm: 'btree', columns: [
        'eventType',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'meeting_id', algorithm: 'btree', columns: [
        'meetingId',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
    ],
    constraints: [
      { name: 'meeting_activity_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MeetingActivityRow),
  meeting_availability_rule: __table({
    name: 'meeting_availability_rule',
    indexes: [
      { name: 'event_type_id', algorithm: 'btree', columns: [
        'eventTypeId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
      { name: 'weekday', algorithm: 'btree', columns: [
        'weekday',
      ] },
    ],
    constraints: [
      { name: 'meeting_availability_rule_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MeetingAvailabilityRuleRow),
  meeting_booking: __table({
    name: 'meeting_booking',
    indexes: [
      { name: 'booked_by_user_id', algorithm: 'btree', columns: [
        'bookedByUserId',
      ] },
      { name: 'booking_token', algorithm: 'btree', columns: [
        'bookingToken',
      ] },
      { name: 'ends_at', algorithm: 'btree', columns: [
        'endsAt',
      ] },
      { name: 'event_type_id', algorithm: 'btree', columns: [
        'eventTypeId',
      ] },
      { name: 'host_user_id', algorithm: 'btree', columns: [
        'hostUserId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'invitee_email', algorithm: 'btree', columns: [
        'inviteeEmail',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
      { name: 'scheduled_meeting_id', algorithm: 'btree', columns: [
        'scheduledMeetingId',
      ] },
      { name: 'starts_at', algorithm: 'btree', columns: [
        'startsAt',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
    ],
    constraints: [
      { name: 'meeting_booking_booking_token_key', constraint: 'unique', columns: ['bookingToken'] },
      { name: 'meeting_booking_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MeetingBookingRow),
  meeting_event_type: __table({
    name: 'meeting_event_type',
    indexes: [
      { name: 'default_channel_id', algorithm: 'btree', columns: [
        'defaultChannelId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
      { name: 'owner_user_id', algorithm: 'btree', columns: [
        'ownerUserId',
      ] },
      { name: 'slug', algorithm: 'btree', columns: [
        'slug',
      ] },
      { name: 'visibility', algorithm: 'btree', columns: [
        'visibility',
      ] },
    ],
    constraints: [
      { name: 'meeting_event_type_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MeetingEventTypeRow),
  meeting_followup_template: __table({
    name: 'meeting_followup_template',
    indexes: [
      { name: 'created_by_user_id', algorithm: 'btree', columns: [
        'createdByUserId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
    ],
    constraints: [
      { name: 'meeting_followup_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MeetingFollowupTemplateRow),
  meeting_public_profile: __table({
    name: 'meeting_public_profile',
    indexes: [
      { name: 'handle', algorithm: 'btree', columns: [
        'handle',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'meeting_public_profile_handle_key', constraint: 'unique', columns: ['handle'] },
      { name: 'meeting_public_profile_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, MeetingPublicProfileRow),
  meeting_recording_policy: __table({
    name: 'meeting_recording_policy',
    indexes: [
      { name: 'created_by_user_id', algorithm: 'btree', columns: [
        'createdByUserId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
    ],
    constraints: [
      { name: 'meeting_recording_policy_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MeetingRecordingPolicyRow),
  meeting_reminder_delivery: __table({
    name: 'meeting_reminder_delivery',
    indexes: [
      { name: 'booking_id', algorithm: 'btree', columns: [
        'bookingId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
      { name: 'status', algorithm: 'btree', columns: [
        'status',
      ] },
      { name: 'template_id', algorithm: 'btree', columns: [
        'templateId',
      ] },
      { name: 'trigger_at', algorithm: 'btree', columns: [
        'triggerAt',
      ] },
    ],
    constraints: [
      { name: 'meeting_reminder_delivery_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MeetingReminderDeliveryRow),
  meeting_reminder_template: __table({
    name: 'meeting_reminder_template',
    indexes: [
      { name: 'created_by_user_id', algorithm: 'btree', columns: [
        'createdByUserId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
    ],
    constraints: [
      { name: 'meeting_reminder_template_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MeetingReminderTemplateRow),
  organization: __table({
    name: 'organization',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'organization_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrganizationRow),
  organization_member: __table({
    name: 'organization_member',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'organization_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OrganizationMemberRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'email', algorithm: 'btree', columns: [
        'email',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_email_key', constraint: 'unique', columns: ['email'] },
      { name: 'user_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  user_presence: __table({
    name: 'user_presence',
    indexes: [
      { name: 'channel_id', algorithm: 'btree', columns: [
        'channelId',
      ] },
      { name: 'org_id', algorithm: 'btree', columns: [
        'orgId',
      ] },
      { name: 'user_id', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'user_presence_user_id_key', constraint: 'unique', columns: ['userId'] },
    ],
  }, UserPresenceRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_channel_member", AddChannelMemberReducer),
  __reducerSchema("approve_meeting_booking", ApproveMeetingBookingReducer),
  __reducerSchema("cancel_meeting_booking", CancelMeetingBookingReducer),
  __reducerSchema("cancel_meeting_booking_by_token", CancelMeetingBookingByTokenReducer),
  __reducerSchema("cancel_scheduled_meeting", CancelScheduledMeetingReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_invite", CreateInviteReducer),
  __reducerSchema("create_meeting_booking", CreateMeetingBookingReducer),
  __reducerSchema("create_meeting_event_type", CreateMeetingEventTypeReducer),
  __reducerSchema("create_meeting_followup_template", CreateMeetingFollowupTemplateReducer),
  __reducerSchema("create_organization", CreateOrganizationReducer),
  __reducerSchema("create_scheduled_meeting", CreateScheduledMeetingReducer),
  __reducerSchema("edit_message", EditMessageReducer),
  __reducerSchema("end_channel_call", EndChannelCallReducer),
  __reducerSchema("generate_join_id", GenerateJoinIdReducer),
  __reducerSchema("heartbeat", HeartbeatReducer),
  __reducerSchema("join_channel_call", JoinChannelCallReducer),
  __reducerSchema("join_organization", JoinOrganizationReducer),
  __reducerSchema("join_scheduled_meeting", JoinScheduledMeetingReducer),
  __reducerSchema("leave_channel_call", LeaveChannelCallReducer),
  __reducerSchema("mark_channel_read", MarkChannelReadReducer),
  __reducerSchema("mark_meeting_reminder_delivery_status", MarkMeetingReminderDeliveryStatusReducer),
  __reducerSchema("queue_meeting_reminder_deliveries", QueueMeetingReminderDeliveriesReducer),
  __reducerSchema("register_user", RegisterUserReducer),
  __reducerSchema("reject_meeting_booking", RejectMeetingBookingReducer),
  __reducerSchema("reschedule_meeting_booking", RescheduleMeetingBookingReducer),
  __reducerSchema("reschedule_meeting_booking_by_token", RescheduleMeetingBookingByTokenReducer),
  __reducerSchema("reschedule_scheduled_meeting", RescheduleScheduledMeetingReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_meeting_availability_rules", SetMeetingAvailabilityRulesReducer),
  __reducerSchema("set_meeting_recording_policy", SetMeetingRecordingPolicyReducer),
  __reducerSchema("set_meeting_reminder_template", SetMeetingReminderTemplateReducer),
  __reducerSchema("set_typing", SetTypingReducer),
  __reducerSchema("start_channel_call", StartChannelCallReducer),
  __reducerSchema("toggle_reaction", ToggleReactionReducer),
  __reducerSchema("update_meeting_event_type", UpdateMeetingEventTypeReducer),
  __reducerSchema("update_profile", UpdateProfileReducer),
  __reducerSchema("update_scheduled_meeting", UpdateScheduledMeetingReducer),
  __reducerSchema("upsert_meeting_public_profile", UpsertMeetingPublicProfileReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

