// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  orgId: __t.u64(),
  agentId: __t.u64(),
  taskId: __t.u64(),
  approvalId: __t.u64(),
  projectId: __t.u64(),
  goalId: __t.u64(),
  runId: __t.u64(),
  eventType: __t.string(),
  description: __t.string(),
  metadataJson: __t.string(),
};
