// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  eventTypeId: __t.u64().name("event_type_id"),
  userId: __t.u64().name("user_id"),
  weekday: __t.u64(),
  startMinute: __t.u64().name("start_minute"),
  endMinute: __t.u64().name("end_minute"),
  timezone: __t.string(),
  isEnabled: __t.bool().name("is_enabled"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
