// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  ownerUserId: __t.u64().name("owner_user_id"),
  slug: __t.string(),
  title: __t.string(),
  description: __t.string(),
  durationMin: __t.u64().name("duration_min"),
  visibility: __t.string(),
  defaultChannelId: __t.u64().name("default_channel_id"),
  requireApproval: __t.bool().name("require_approval"),
  isActive: __t.bool().name("is_active"),
  maxDaysInAdvance: __t.u64().name("max_days_in_advance"),
  minNoticeMin: __t.u64().name("min_notice_min"),
  bufferBeforeMin: __t.u64().name("buffer_before_min"),
  bufferAfterMin: __t.u64().name("buffer_after_min"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
