// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  eventTypeId: __t.u64().name("event_type_id"),
  scheduledMeetingId: __t.u64().name("scheduled_meeting_id"),
  hostUserId: __t.u64().name("host_user_id"),
  bookedByUserId: __t.u64().name("booked_by_user_id"),
  inviteeName: __t.string().name("invitee_name"),
  inviteeEmail: __t.string().name("invitee_email"),
  inviteeTimezone: __t.string().name("invitee_timezone"),
  startsAt: __t.u64().name("starts_at"),
  endsAt: __t.u64().name("ends_at"),
  status: __t.string(),
  bookingToken: __t.string().name("booking_token"),
  notes: __t.string(),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
