// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  actorUserId: __t.u64().name("actor_user_id"),
  bookingId: __t.u64().name("booking_id"),
  meetingId: __t.u64().name("meeting_id"),
  eventType: __t.string().name("event_type"),
  description: __t.string(),
  metadataJson: __t.string().name("metadata_json"),
  createdAt: __t.u64().name("created_at"),
});
