// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  orgId: __t.u64().name("org_id"),
  bookingId: __t.u64().name("booking_id"),
  templateId: __t.u64().name("template_id"),
  offsetMin: __t.u64().name("offset_min"),
  triggerAt: __t.u64().name("trigger_at"),
  status: __t.string(),
  attempts: __t.u64(),
  lastError: __t.string().name("last_error"),
  sentAt: __t.u64().name("sent_at"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
