// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatChannel = __t.object("ChatChannel", {
  id: __t.u64(),
  orgId: __t.u64(),
  name: __t.string(),
  type: __t.string(),
  createdBy: __t.u64(),
  createdAt: __t.u64(),
});
export type ChatChannel = __Infer<typeof ChatChannel>;

export const ChatChannelMember = __t.object("ChatChannelMember", {
  id: __t.u64(),
  channelId: __t.u64(),
  userId: __t.u64(),
  joinedAt: __t.u64(),
});
export type ChatChannelMember = __Infer<typeof ChatChannelMember>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  channelId: __t.u64(),
  senderId: __t.u64(),
  content: __t.string(),
  createdAt: __t.u64(),
  parentMessageId: __t.u64(),
  editedAt: __t.u64(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ChatReaction = __t.object("ChatReaction", {
  id: __t.u64(),
  messageId: __t.u64(),
  userId: __t.u64(),
  emoji: __t.string(),
  isActive: __t.bool(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ChatReaction = __Infer<typeof ChatReaction>;

export const ChatReadState = __t.object("ChatReadState", {
  id: __t.u64(),
  channelId: __t.u64(),
  userId: __t.u64(),
  lastReadAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ChatReadState = __Infer<typeof ChatReadState>;

export const ChatTyping = __t.object("ChatTyping", {
  id: __t.u64(),
  channelId: __t.u64(),
  userId: __t.u64(),
  isTyping: __t.bool(),
  updatedAt: __t.u64(),
});
export type ChatTyping = __Infer<typeof ChatTyping>;

export const Invite = __t.object("Invite", {
  id: __t.u64(),
  orgId: __t.u64(),
  inviterUserId: __t.u64(),
  email: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type Invite = __Infer<typeof Invite>;

export const JoinId = __t.object("JoinId", {
  id: __t.u64(),
  orgId: __t.u64(),
  token: __t.string(),
  isRevoked: __t.bool(),
  createdAt: __t.u64(),
});
export type JoinId = __Infer<typeof JoinId>;

export const Organization = __t.object("Organization", {
  id: __t.u64(),
  name: __t.string(),
  createdAt: __t.u64(),
});
export type Organization = __Infer<typeof Organization>;

export const OrganizationMember = __t.object("OrganizationMember", {
  id: __t.u64(),
  orgId: __t.u64(),
  userId: __t.u64(),
  role: __t.string(),
  joinedAt: __t.u64(),
});
export type OrganizationMember = __Infer<typeof OrganizationMember>;

export const User = __t.object("User", {
  id: __t.u64(),
  identity: __t.identity(),
  email: __t.string(),
  name: __t.string(),
  createdAt: __t.u64(),
  lastLoginAt: __t.u64(),
});
export type User = __Infer<typeof User>;

export const UserPresence = __t.object("UserPresence", {
  userId: __t.u64(),
  orgId: __t.u64(),
  channelId: __t.u64(),
  status: __t.string(),
  lastSeenAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type UserPresence = __Infer<typeof UserPresence>;

