// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  eventTypeId: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  durationMin: __t.u64(),
  visibility: __t.string(),
  defaultChannelId: __t.u64(),
  requireApproval: __t.bool(),
  isActive: __t.bool(),
  maxDaysInAdvance: __t.u64(),
  minNoticeMin: __t.u64(),
  bufferBeforeMin: __t.u64(),
  bufferAfterMin: __t.u64(),
};
