// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  runId: __t.u64(),
  status: __t.string(),
  summary: __t.string(),
  errorMessage: __t.string(),
  tokenInput: __t.u64(),
  tokenOutput: __t.u64(),
  toolCalls: __t.u64(),
  costMicrousd: __t.u64(),
};
