// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  orgId: __t.u64(),
  defaultModel: __t.string(),
  autonomyPosture: __t.string(),
  fallbackMode: __t.string(),
  externalSendPolicy: __t.string(),
  budgetChangePolicy: __t.string(),
  internalNotesPolicy: __t.string(),
  integrationsJson: __t.string(),
  auditRetentionDays: __t.u64(),
  maxRunCostMicrousd: __t.u64(),
};
