// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  orgId: __t.u64(),
  agentId: __t.u64(),
  runId: __t.u64(),
  adapterType: __t.string(),
  externalSessionId: __t.string(),
  status: __t.string(),
  summary: __t.string(),
  metadataJson: __t.string(),
  lastSeenAt: __t.u64(),
};
