// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.u64().primaryKey().name("user_id"),
  orgId: __t.u64().name("org_id"),
  channelId: __t.u64().name("channel_id"),
  status: __t.string(),
  lastSeenAt: __t.u64().name("last_seen_at"),
  updatedAt: __t.u64().name("updated_at"),
});
