// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddChannelMemberReducer from "../add_channel_member_reducer";
import ApproveMeetingBookingReducer from "../approve_meeting_booking_reducer";
import CancelMeetingBookingReducer from "../cancel_meeting_booking_reducer";
import CancelMeetingBookingByTokenReducer from "../cancel_meeting_booking_by_token_reducer";
import CancelScheduledMeetingReducer from "../cancel_scheduled_meeting_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateInviteReducer from "../create_invite_reducer";
import CreateMeetingBookingReducer from "../create_meeting_booking_reducer";
import CreateMeetingEventTypeReducer from "../create_meeting_event_type_reducer";
import CreateMeetingFollowupTemplateReducer from "../create_meeting_followup_template_reducer";
import CreateOrganizationReducer from "../create_organization_reducer";
import CreateScheduledMeetingReducer from "../create_scheduled_meeting_reducer";
import EditMessageReducer from "../edit_message_reducer";
import EndChannelCallReducer from "../end_channel_call_reducer";
import GenerateJoinIdReducer from "../generate_join_id_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import JoinChannelCallReducer from "../join_channel_call_reducer";
import JoinOrganizationReducer from "../join_organization_reducer";
import JoinScheduledMeetingReducer from "../join_scheduled_meeting_reducer";
import LeaveChannelCallReducer from "../leave_channel_call_reducer";
import MarkChannelReadReducer from "../mark_channel_read_reducer";
import MarkMeetingReminderDeliveryStatusReducer from "../mark_meeting_reminder_delivery_status_reducer";
import QueueMeetingReminderDeliveriesReducer from "../queue_meeting_reminder_deliveries_reducer";
import RegisterUserReducer from "../register_user_reducer";
import RejectMeetingBookingReducer from "../reject_meeting_booking_reducer";
import RescheduleMeetingBookingReducer from "../reschedule_meeting_booking_reducer";
import RescheduleMeetingBookingByTokenReducer from "../reschedule_meeting_booking_by_token_reducer";
import RescheduleScheduledMeetingReducer from "../reschedule_scheduled_meeting_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetMeetingAvailabilityRulesReducer from "../set_meeting_availability_rules_reducer";
import SetMeetingRecordingPolicyReducer from "../set_meeting_recording_policy_reducer";
import SetMeetingReminderTemplateReducer from "../set_meeting_reminder_template_reducer";
import SetTypingReducer from "../set_typing_reducer";
import StartChannelCallReducer from "../start_channel_call_reducer";
import ToggleReactionReducer from "../toggle_reaction_reducer";
import UpdateMeetingEventTypeReducer from "../update_meeting_event_type_reducer";
import UpdateProfileReducer from "../update_profile_reducer";
import UpdateScheduledMeetingReducer from "../update_scheduled_meeting_reducer";
import UpsertMeetingPublicProfileReducer from "../upsert_meeting_public_profile_reducer";

export type AddChannelMemberParams = __Infer<typeof AddChannelMemberReducer>;
export type ApproveMeetingBookingParams = __Infer<typeof ApproveMeetingBookingReducer>;
export type CancelMeetingBookingParams = __Infer<typeof CancelMeetingBookingReducer>;
export type CancelMeetingBookingByTokenParams = __Infer<typeof CancelMeetingBookingByTokenReducer>;
export type CancelScheduledMeetingParams = __Infer<typeof CancelScheduledMeetingReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateInviteParams = __Infer<typeof CreateInviteReducer>;
export type CreateMeetingBookingParams = __Infer<typeof CreateMeetingBookingReducer>;
export type CreateMeetingEventTypeParams = __Infer<typeof CreateMeetingEventTypeReducer>;
export type CreateMeetingFollowupTemplateParams = __Infer<typeof CreateMeetingFollowupTemplateReducer>;
export type CreateOrganizationParams = __Infer<typeof CreateOrganizationReducer>;
export type CreateScheduledMeetingParams = __Infer<typeof CreateScheduledMeetingReducer>;
export type EditMessageParams = __Infer<typeof EditMessageReducer>;
export type EndChannelCallParams = __Infer<typeof EndChannelCallReducer>;
export type GenerateJoinIdParams = __Infer<typeof GenerateJoinIdReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type JoinChannelCallParams = __Infer<typeof JoinChannelCallReducer>;
export type JoinOrganizationParams = __Infer<typeof JoinOrganizationReducer>;
export type JoinScheduledMeetingParams = __Infer<typeof JoinScheduledMeetingReducer>;
export type LeaveChannelCallParams = __Infer<typeof LeaveChannelCallReducer>;
export type MarkChannelReadParams = __Infer<typeof MarkChannelReadReducer>;
export type MarkMeetingReminderDeliveryStatusParams = __Infer<typeof MarkMeetingReminderDeliveryStatusReducer>;
export type QueueMeetingReminderDeliveriesParams = __Infer<typeof QueueMeetingReminderDeliveriesReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type RejectMeetingBookingParams = __Infer<typeof RejectMeetingBookingReducer>;
export type RescheduleMeetingBookingParams = __Infer<typeof RescheduleMeetingBookingReducer>;
export type RescheduleMeetingBookingByTokenParams = __Infer<typeof RescheduleMeetingBookingByTokenReducer>;
export type RescheduleScheduledMeetingParams = __Infer<typeof RescheduleScheduledMeetingReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetMeetingAvailabilityRulesParams = __Infer<typeof SetMeetingAvailabilityRulesReducer>;
export type SetMeetingRecordingPolicyParams = __Infer<typeof SetMeetingRecordingPolicyReducer>;
export type SetMeetingReminderTemplateParams = __Infer<typeof SetMeetingReminderTemplateReducer>;
export type SetTypingParams = __Infer<typeof SetTypingReducer>;
export type StartChannelCallParams = __Infer<typeof StartChannelCallReducer>;
export type ToggleReactionParams = __Infer<typeof ToggleReactionReducer>;
export type UpdateMeetingEventTypeParams = __Infer<typeof UpdateMeetingEventTypeReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;
export type UpdateScheduledMeetingParams = __Infer<typeof UpdateScheduledMeetingReducer>;
export type UpsertMeetingPublicProfileParams = __Infer<typeof UpsertMeetingPublicProfileReducer>;

