// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddChannelMemberReducer from "../add_channel_member_reducer";
import CreateChannelReducer from "../create_channel_reducer";
import CreateInviteReducer from "../create_invite_reducer";
import CreateOrganizationReducer from "../create_organization_reducer";
import GenerateJoinIdReducer from "../generate_join_id_reducer";
import JoinOrganizationReducer from "../join_organization_reducer";
import RegisterUserReducer from "../register_user_reducer";
import SendMessageReducer from "../send_message_reducer";
import UpdateProfileReducer from "../update_profile_reducer";

export type AddChannelMemberParams = __Infer<typeof AddChannelMemberReducer>;
export type CreateChannelParams = __Infer<typeof CreateChannelReducer>;
export type CreateInviteParams = __Infer<typeof CreateInviteReducer>;
export type CreateOrganizationParams = __Infer<typeof CreateOrganizationReducer>;
export type GenerateJoinIdParams = __Infer<typeof GenerateJoinIdReducer>;
export type JoinOrganizationParams = __Infer<typeof JoinOrganizationReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;

