/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingsIndexRouteImport } from './routes/meetings.index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as MeetingsSettingsRouteImport } from './routes/meetings.settings'
import { Route as MeetingsRequestsRouteImport } from './routes/meetings.requests'
import { Route as MeetingsCalendarRouteImport } from './routes/meetings.calendar'
import { Route as MeetingsActivityRouteImport } from './routes/meetings.activity'
import { Route as MeetInviteTokenRouteImport } from './routes/meet.$inviteToken'
import { Route as BookingTokenRouteImport } from './routes/booking.$token'
import { Route as AiTasksRouteImport } from './routes/ai.tasks'
import { Route as AiSettingsRouteImport } from './routes/ai.settings'
import { Route as AiSecretsRouteImport } from './routes/ai.secrets'
import { Route as AiProjectsRouteImport } from './routes/ai.projects'
import { Route as AiOrgRouteImport } from './routes/ai.org'
import { Route as AiLlmsRouteImport } from './routes/ai.llms'
import { Route as AiInboxRouteImport } from './routes/ai.inbox'
import { Route as AiGoalsRouteImport } from './routes/ai.goals'
import { Route as AiCostsRouteImport } from './routes/ai.costs'
import { Route as AiApprovalsRouteImport } from './routes/ai.approvals'
import { Route as AiAgentsRouteImport } from './routes/ai.agents'
import { Route as AiActivityRouteImport } from './routes/ai.activity'
import { Route as UHandleIndexRouteImport } from './routes/u.$handle.index'
import { Route as UHandleEventTypeSlugRouteImport } from './routes/u.$handle.$eventTypeSlug'
import { Route as AiTasksTaskIdRouteImport } from './routes/ai.tasks.$taskId'
import { Route as AiProjectsProjectIdRouteImport } from './routes/ai.projects.$projectId'
import { Route as AiGoalsGoalIdRouteImport } from './routes/ai.goals.$goalId'
import { Route as AiApprovalsApprovalIdRouteImport } from './routes/ai.approvals.$approvalId'
import { Route as AiAgentsAgentIdRouteImport } from './routes/ai.agents.$agentId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeetingsRoute,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRoute,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsSettingsRoute = MeetingsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MeetingsRoute,
} as any)
const MeetingsRequestsRoute = MeetingsRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => MeetingsRoute,
} as any)
const MeetingsCalendarRoute = MeetingsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => MeetingsRoute,
} as any)
const MeetingsActivityRoute = MeetingsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => MeetingsRoute,
} as any)
const MeetInviteTokenRoute = MeetInviteTokenRouteImport.update({
  id: '/meet/$inviteToken',
  path: '/meet/$inviteToken',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingTokenRoute = BookingTokenRouteImport.update({
  id: '/booking/$token',
  path: '/booking/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTasksRoute = AiTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AiRoute,
} as any)
const AiSettingsRoute = AiSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AiRoute,
} as any)
const AiSecretsRoute = AiSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => AiRoute,
} as any)
const AiProjectsRoute = AiProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AiRoute,
} as any)
const AiOrgRoute = AiOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AiRoute,
} as any)
const AiLlmsRoute = AiLlmsRouteImport.update({
  id: '/llms',
  path: '/llms',
  getParentRoute: () => AiRoute,
} as any)
const AiInboxRoute = AiInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AiRoute,
} as any)
const AiGoalsRoute = AiGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AiRoute,
} as any)
const AiCostsRoute = AiCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AiRoute,
} as any)
const AiApprovalsRoute = AiApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AiRoute,
} as any)
const AiAgentsRoute = AiAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AiRoute,
} as any)
const AiActivityRoute = AiActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AiRoute,
} as any)
const UHandleIndexRoute = UHandleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UHandleRoute,
} as any)
const UHandleEventTypeSlugRoute = UHandleEventTypeSlugRouteImport.update({
  id: '/$eventTypeSlug',
  path: '/$eventTypeSlug',
  getParentRoute: () => UHandleRoute,
} as any)
const AiTasksTaskIdRoute = AiTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AiTasksRoute,
} as any)
const AiProjectsProjectIdRoute = AiProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AiProjectsRoute,
} as any)
const AiGoalsGoalIdRoute = AiGoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => AiGoalsRoute,
} as any)
const AiApprovalsApprovalIdRoute = AiApprovalsApprovalIdRouteImport.update({
  id: '/$approvalId',
  path: '/$approvalId',
  getParentRoute: () => AiApprovalsRoute,
} as any)
const AiAgentsAgentIdRoute = AiAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AiAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRouteWithChildren
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ai/activity': typeof AiActivityRoute
  '/ai/agents': typeof AiAgentsRouteWithChildren
  '/ai/approvals': typeof AiApprovalsRouteWithChildren
  '/ai/costs': typeof AiCostsRoute
  '/ai/goals': typeof AiGoalsRouteWithChildren
  '/ai/inbox': typeof AiInboxRoute
  '/ai/llms': typeof AiLlmsRoute
  '/ai/org': typeof AiOrgRoute
  '/ai/projects': typeof AiProjectsRouteWithChildren
  '/ai/secrets': typeof AiSecretsRoute
  '/ai/settings': typeof AiSettingsRoute
  '/ai/tasks': typeof AiTasksRouteWithChildren
  '/booking/$token': typeof BookingTokenRoute
  '/meet/$inviteToken': typeof MeetInviteTokenRoute
  '/meetings/activity': typeof MeetingsActivityRoute
  '/meetings/calendar': typeof MeetingsCalendarRoute
  '/meetings/requests': typeof MeetingsRequestsRoute
  '/meetings/settings': typeof MeetingsSettingsRoute
  '/u/$handle': typeof UHandleRouteWithChildren
  '/ai/': typeof AiIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/ai/agents/$agentId': typeof AiAgentsAgentIdRoute
  '/ai/approvals/$approvalId': typeof AiApprovalsApprovalIdRoute
  '/ai/goals/$goalId': typeof AiGoalsGoalIdRoute
  '/ai/projects/$projectId': typeof AiProjectsProjectIdRoute
  '/ai/tasks/$taskId': typeof AiTasksTaskIdRoute
  '/u/$handle/$eventTypeSlug': typeof UHandleEventTypeSlugRoute
  '/u/$handle/': typeof UHandleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ai/activity': typeof AiActivityRoute
  '/ai/agents': typeof AiAgentsRouteWithChildren
  '/ai/approvals': typeof AiApprovalsRouteWithChildren
  '/ai/costs': typeof AiCostsRoute
  '/ai/goals': typeof AiGoalsRouteWithChildren
  '/ai/inbox': typeof AiInboxRoute
  '/ai/llms': typeof AiLlmsRoute
  '/ai/org': typeof AiOrgRoute
  '/ai/projects': typeof AiProjectsRouteWithChildren
  '/ai/secrets': typeof AiSecretsRoute
  '/ai/settings': typeof AiSettingsRoute
  '/ai/tasks': typeof AiTasksRouteWithChildren
  '/booking/$token': typeof BookingTokenRoute
  '/meet/$inviteToken': typeof MeetInviteTokenRoute
  '/meetings/activity': typeof MeetingsActivityRoute
  '/meetings/calendar': typeof MeetingsCalendarRoute
  '/meetings/requests': typeof MeetingsRequestsRoute
  '/meetings/settings': typeof MeetingsSettingsRoute
  '/ai': typeof AiIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/ai/agents/$agentId': typeof AiAgentsAgentIdRoute
  '/ai/approvals/$approvalId': typeof AiApprovalsApprovalIdRoute
  '/ai/goals/$goalId': typeof AiGoalsGoalIdRoute
  '/ai/projects/$projectId': typeof AiProjectsProjectIdRoute
  '/ai/tasks/$taskId': typeof AiTasksTaskIdRoute
  '/u/$handle/$eventTypeSlug': typeof UHandleEventTypeSlugRoute
  '/u/$handle': typeof UHandleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRouteWithChildren
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ai/activity': typeof AiActivityRoute
  '/ai/agents': typeof AiAgentsRouteWithChildren
  '/ai/approvals': typeof AiApprovalsRouteWithChildren
  '/ai/costs': typeof AiCostsRoute
  '/ai/goals': typeof AiGoalsRouteWithChildren
  '/ai/inbox': typeof AiInboxRoute
  '/ai/llms': typeof AiLlmsRoute
  '/ai/org': typeof AiOrgRoute
  '/ai/projects': typeof AiProjectsRouteWithChildren
  '/ai/secrets': typeof AiSecretsRoute
  '/ai/settings': typeof AiSettingsRoute
  '/ai/tasks': typeof AiTasksRouteWithChildren
  '/booking/$token': typeof BookingTokenRoute
  '/meet/$inviteToken': typeof MeetInviteTokenRoute
  '/meetings/activity': typeof MeetingsActivityRoute
  '/meetings/calendar': typeof MeetingsCalendarRoute
  '/meetings/requests': typeof MeetingsRequestsRoute
  '/meetings/settings': typeof MeetingsSettingsRoute
  '/u/$handle': typeof UHandleRouteWithChildren
  '/ai/': typeof AiIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/ai/agents/$agentId': typeof AiAgentsAgentIdRoute
  '/ai/approvals/$approvalId': typeof AiApprovalsApprovalIdRoute
  '/ai/goals/$goalId': typeof AiGoalsGoalIdRoute
  '/ai/projects/$projectId': typeof AiProjectsProjectIdRoute
  '/ai/tasks/$taskId': typeof AiTasksTaskIdRoute
  '/u/$handle/$eventTypeSlug': typeof UHandleEventTypeSlugRoute
  '/u/$handle/': typeof UHandleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/chat'
    | '/login'
    | '/meetings'
    | '/members'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/ai/activity'
    | '/ai/agents'
    | '/ai/approvals'
    | '/ai/costs'
    | '/ai/goals'
    | '/ai/inbox'
    | '/ai/llms'
    | '/ai/org'
    | '/ai/projects'
    | '/ai/secrets'
    | '/ai/settings'
    | '/ai/tasks'
    | '/booking/$token'
    | '/meet/$inviteToken'
    | '/meetings/activity'
    | '/meetings/calendar'
    | '/meetings/requests'
    | '/meetings/settings'
    | '/u/$handle'
    | '/ai/'
    | '/meetings/'
    | '/ai/agents/$agentId'
    | '/ai/approvals/$approvalId'
    | '/ai/goals/$goalId'
    | '/ai/projects/$projectId'
    | '/ai/tasks/$taskId'
    | '/u/$handle/$eventTypeSlug'
    | '/u/$handle/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/login'
    | '/members'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/ai/activity'
    | '/ai/agents'
    | '/ai/approvals'
    | '/ai/costs'
    | '/ai/goals'
    | '/ai/inbox'
    | '/ai/llms'
    | '/ai/org'
    | '/ai/projects'
    | '/ai/secrets'
    | '/ai/settings'
    | '/ai/tasks'
    | '/booking/$token'
    | '/meet/$inviteToken'
    | '/meetings/activity'
    | '/meetings/calendar'
    | '/meetings/requests'
    | '/meetings/settings'
    | '/ai'
    | '/meetings'
    | '/ai/agents/$agentId'
    | '/ai/approvals/$approvalId'
    | '/ai/goals/$goalId'
    | '/ai/projects/$projectId'
    | '/ai/tasks/$taskId'
    | '/u/$handle/$eventTypeSlug'
    | '/u/$handle'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/chat'
    | '/login'
    | '/meetings'
    | '/members'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/ai/activity'
    | '/ai/agents'
    | '/ai/approvals'
    | '/ai/costs'
    | '/ai/goals'
    | '/ai/inbox'
    | '/ai/llms'
    | '/ai/org'
    | '/ai/projects'
    | '/ai/secrets'
    | '/ai/settings'
    | '/ai/tasks'
    | '/booking/$token'
    | '/meet/$inviteToken'
    | '/meetings/activity'
    | '/meetings/calendar'
    | '/meetings/requests'
    | '/meetings/settings'
    | '/u/$handle'
    | '/ai/'
    | '/meetings/'
    | '/ai/agents/$agentId'
    | '/ai/approvals/$approvalId'
    | '/ai/goals/$goalId'
    | '/ai/projects/$projectId'
    | '/ai/tasks/$taskId'
    | '/u/$handle/$eventTypeSlug'
    | '/u/$handle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRouteWithChildren
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRouteWithChildren
  MembersRoute: typeof MembersRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BookingTokenRoute: typeof BookingTokenRoute
  MeetInviteTokenRoute: typeof MeetInviteTokenRoute
  UHandleRoute: typeof UHandleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRoute
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/settings': {
      id: '/meetings/settings'
      path: '/settings'
      fullPath: '/meetings/settings'
      preLoaderRoute: typeof MeetingsSettingsRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/meetings/requests': {
      id: '/meetings/requests'
      path: '/requests'
      fullPath: '/meetings/requests'
      preLoaderRoute: typeof MeetingsRequestsRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/meetings/calendar': {
      id: '/meetings/calendar'
      path: '/calendar'
      fullPath: '/meetings/calendar'
      preLoaderRoute: typeof MeetingsCalendarRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/meetings/activity': {
      id: '/meetings/activity'
      path: '/activity'
      fullPath: '/meetings/activity'
      preLoaderRoute: typeof MeetingsActivityRouteImport
      parentRoute: typeof MeetingsRoute
    }
    '/meet/$inviteToken': {
      id: '/meet/$inviteToken'
      path: '/meet/$inviteToken'
      fullPath: '/meet/$inviteToken'
      preLoaderRoute: typeof MeetInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$token': {
      id: '/booking/$token'
      path: '/booking/$token'
      fullPath: '/booking/$token'
      preLoaderRoute: typeof BookingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/tasks': {
      id: '/ai/tasks'
      path: '/tasks'
      fullPath: '/ai/tasks'
      preLoaderRoute: typeof AiTasksRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/settings': {
      id: '/ai/settings'
      path: '/settings'
      fullPath: '/ai/settings'
      preLoaderRoute: typeof AiSettingsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/secrets': {
      id: '/ai/secrets'
      path: '/secrets'
      fullPath: '/ai/secrets'
      preLoaderRoute: typeof AiSecretsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/projects': {
      id: '/ai/projects'
      path: '/projects'
      fullPath: '/ai/projects'
      preLoaderRoute: typeof AiProjectsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/org': {
      id: '/ai/org'
      path: '/org'
      fullPath: '/ai/org'
      preLoaderRoute: typeof AiOrgRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/llms': {
      id: '/ai/llms'
      path: '/llms'
      fullPath: '/ai/llms'
      preLoaderRoute: typeof AiLlmsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/inbox': {
      id: '/ai/inbox'
      path: '/inbox'
      fullPath: '/ai/inbox'
      preLoaderRoute: typeof AiInboxRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/goals': {
      id: '/ai/goals'
      path: '/goals'
      fullPath: '/ai/goals'
      preLoaderRoute: typeof AiGoalsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/costs': {
      id: '/ai/costs'
      path: '/costs'
      fullPath: '/ai/costs'
      preLoaderRoute: typeof AiCostsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/approvals': {
      id: '/ai/approvals'
      path: '/approvals'
      fullPath: '/ai/approvals'
      preLoaderRoute: typeof AiApprovalsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/agents': {
      id: '/ai/agents'
      path: '/agents'
      fullPath: '/ai/agents'
      preLoaderRoute: typeof AiAgentsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/activity': {
      id: '/ai/activity'
      path: '/activity'
      fullPath: '/ai/activity'
      preLoaderRoute: typeof AiActivityRouteImport
      parentRoute: typeof AiRoute
    }
    '/u/$handle/': {
      id: '/u/$handle/'
      path: '/'
      fullPath: '/u/$handle/'
      preLoaderRoute: typeof UHandleIndexRouteImport
      parentRoute: typeof UHandleRoute
    }
    '/u/$handle/$eventTypeSlug': {
      id: '/u/$handle/$eventTypeSlug'
      path: '/$eventTypeSlug'
      fullPath: '/u/$handle/$eventTypeSlug'
      preLoaderRoute: typeof UHandleEventTypeSlugRouteImport
      parentRoute: typeof UHandleRoute
    }
    '/ai/tasks/$taskId': {
      id: '/ai/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/ai/tasks/$taskId'
      preLoaderRoute: typeof AiTasksTaskIdRouteImport
      parentRoute: typeof AiTasksRoute
    }
    '/ai/projects/$projectId': {
      id: '/ai/projects/$projectId'
      path: '/$projectId'
      fullPath: '/ai/projects/$projectId'
      preLoaderRoute: typeof AiProjectsProjectIdRouteImport
      parentRoute: typeof AiProjectsRoute
    }
    '/ai/goals/$goalId': {
      id: '/ai/goals/$goalId'
      path: '/$goalId'
      fullPath: '/ai/goals/$goalId'
      preLoaderRoute: typeof AiGoalsGoalIdRouteImport
      parentRoute: typeof AiGoalsRoute
    }
    '/ai/approvals/$approvalId': {
      id: '/ai/approvals/$approvalId'
      path: '/$approvalId'
      fullPath: '/ai/approvals/$approvalId'
      preLoaderRoute: typeof AiApprovalsApprovalIdRouteImport
      parentRoute: typeof AiApprovalsRoute
    }
    '/ai/agents/$agentId': {
      id: '/ai/agents/$agentId'
      path: '/$agentId'
      fullPath: '/ai/agents/$agentId'
      preLoaderRoute: typeof AiAgentsAgentIdRouteImport
      parentRoute: typeof AiAgentsRoute
    }
  }
}

interface AiAgentsRouteChildren {
  AiAgentsAgentIdRoute: typeof AiAgentsAgentIdRoute
}

const AiAgentsRouteChildren: AiAgentsRouteChildren = {
  AiAgentsAgentIdRoute: AiAgentsAgentIdRoute,
}

const AiAgentsRouteWithChildren = AiAgentsRoute._addFileChildren(
  AiAgentsRouteChildren,
)

interface AiApprovalsRouteChildren {
  AiApprovalsApprovalIdRoute: typeof AiApprovalsApprovalIdRoute
}

const AiApprovalsRouteChildren: AiApprovalsRouteChildren = {
  AiApprovalsApprovalIdRoute: AiApprovalsApprovalIdRoute,
}

const AiApprovalsRouteWithChildren = AiApprovalsRoute._addFileChildren(
  AiApprovalsRouteChildren,
)

interface AiGoalsRouteChildren {
  AiGoalsGoalIdRoute: typeof AiGoalsGoalIdRoute
}

const AiGoalsRouteChildren: AiGoalsRouteChildren = {
  AiGoalsGoalIdRoute: AiGoalsGoalIdRoute,
}

const AiGoalsRouteWithChildren =
  AiGoalsRoute._addFileChildren(AiGoalsRouteChildren)

interface AiProjectsRouteChildren {
  AiProjectsProjectIdRoute: typeof AiProjectsProjectIdRoute
}

const AiProjectsRouteChildren: AiProjectsRouteChildren = {
  AiProjectsProjectIdRoute: AiProjectsProjectIdRoute,
}

const AiProjectsRouteWithChildren = AiProjectsRoute._addFileChildren(
  AiProjectsRouteChildren,
)

interface AiTasksRouteChildren {
  AiTasksTaskIdRoute: typeof AiTasksTaskIdRoute
}

const AiTasksRouteChildren: AiTasksRouteChildren = {
  AiTasksTaskIdRoute: AiTasksTaskIdRoute,
}

const AiTasksRouteWithChildren =
  AiTasksRoute._addFileChildren(AiTasksRouteChildren)

interface AiRouteChildren {
  AiActivityRoute: typeof AiActivityRoute
  AiAgentsRoute: typeof AiAgentsRouteWithChildren
  AiApprovalsRoute: typeof AiApprovalsRouteWithChildren
  AiCostsRoute: typeof AiCostsRoute
  AiGoalsRoute: typeof AiGoalsRouteWithChildren
  AiInboxRoute: typeof AiInboxRoute
  AiLlmsRoute: typeof AiLlmsRoute
  AiOrgRoute: typeof AiOrgRoute
  AiProjectsRoute: typeof AiProjectsRouteWithChildren
  AiSecretsRoute: typeof AiSecretsRoute
  AiSettingsRoute: typeof AiSettingsRoute
  AiTasksRoute: typeof AiTasksRouteWithChildren
  AiIndexRoute: typeof AiIndexRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiActivityRoute: AiActivityRoute,
  AiAgentsRoute: AiAgentsRouteWithChildren,
  AiApprovalsRoute: AiApprovalsRouteWithChildren,
  AiCostsRoute: AiCostsRoute,
  AiGoalsRoute: AiGoalsRouteWithChildren,
  AiInboxRoute: AiInboxRoute,
  AiLlmsRoute: AiLlmsRoute,
  AiOrgRoute: AiOrgRoute,
  AiProjectsRoute: AiProjectsRouteWithChildren,
  AiSecretsRoute: AiSecretsRoute,
  AiSettingsRoute: AiSettingsRoute,
  AiTasksRoute: AiTasksRouteWithChildren,
  AiIndexRoute: AiIndexRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface MeetingsRouteChildren {
  MeetingsActivityRoute: typeof MeetingsActivityRoute
  MeetingsCalendarRoute: typeof MeetingsCalendarRoute
  MeetingsRequestsRoute: typeof MeetingsRequestsRoute
  MeetingsSettingsRoute: typeof MeetingsSettingsRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
}

const MeetingsRouteChildren: MeetingsRouteChildren = {
  MeetingsActivityRoute: MeetingsActivityRoute,
  MeetingsCalendarRoute: MeetingsCalendarRoute,
  MeetingsRequestsRoute: MeetingsRequestsRoute,
  MeetingsSettingsRoute: MeetingsSettingsRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
}

const MeetingsRouteWithChildren = MeetingsRoute._addFileChildren(
  MeetingsRouteChildren,
)

interface UHandleRouteChildren {
  UHandleEventTypeSlugRoute: typeof UHandleEventTypeSlugRoute
  UHandleIndexRoute: typeof UHandleIndexRoute
}

const UHandleRouteChildren: UHandleRouteChildren = {
  UHandleEventTypeSlugRoute: UHandleEventTypeSlugRoute,
  UHandleIndexRoute: UHandleIndexRoute,
}

const UHandleRouteWithChildren =
  UHandleRoute._addFileChildren(UHandleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRouteWithChildren,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRouteWithChildren,
  MembersRoute: MembersRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BookingTokenRoute: BookingTokenRoute,
  MeetInviteTokenRoute: MeetInviteTokenRoute,
  UHandleRoute: UHandleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
